services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: pg_monitoring
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana_monitoring
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${POSTGRES_HOST}
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_user
      GF_DATABASE_PASSWORD: ${POSTGRES_GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  pg_data:
  grafana_data: