{
 "title": "Simulated General Dashboard Rover",
 "description": "Dashboard with panels to visualize simulated rover data.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Rover Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, is_online FROM get_device_uptime(\r\n  'rover/simulated/is_online',\r\n  to_timestamp($__from/1000),\r\n  to_timestamp($__to/1000),\r\n  INTERVAL '5 seconds',\r\n  INTERVAL '15 seconds'\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Servo Steer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value AS STEER, time FROM rover_readings WHERE sensor_topic = 'rover/simulated/servo/steer';"
    }
   ]
  },
  {
   "title": "LEDs",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "rawSql": "SELECT value AS GREEN_LED, time FROM rover_readings WHERE sensor_topic = 'rover/simulated/led/green';"
    },
    {
     "rawSql": "SELECT value AS RED_LED, time FROM rover_readings WHERE sensor_topic = 'rover/simulated/led/red';"
    },
    {
     "rawSql": "SELECT value AS BLUE_LED, time FROM rover_readings WHERE sensor_topic = 'rover/simulated/led/blue';\n"
    }
   ]
  },
  {
   "title": "Buzzer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "rawSql": "SELECT value AS Buzz, time FROM rover_readings WHERE sensor_topic = 'rover/simulated/buzzer';"
    }
   ]
  },
  {
   "title": "Left Motor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time, value AS LEFT FROM rover_readings WHERE sensor_topic='rover/simulated/motor/left'"
    }
   ]
  },
  {
   "title": "Right Motor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time, value AS LEFT FROM rover_readings WHERE sensor_topic='rover/simulated/motor/right'"
    }
   ]
  },
  {
   "title": "Servo Camera X-Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM rover_readings WHERE sensor_topic = 'rover/simulated/servo/camera_x';"
    }
   ]
  },
  {
   "title": "Servo Camera Y-Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM rover_readings WHERE sensor_topic = 'rover/simulated/servo/camera_y';"
    }
   ]
  }
 ]
}